Add summaries to summer-2022 videos
yougotthisconf/yougotthis.io pull request #38
Opened 2022-10-11 09:56 UTC by harshitajain165

2022-10-18 15:14 UTC, phazonoverload requested changes
Really fantastic contribution, thank you! I've suggested a couple of small changes for formatting and conciseness.

2022-10-18 15:14 UTC, phazonoverload commented on content/library/videos/summer-2021/align-values-with-job.md
> +- Step 1: Know your values
The formatting of these looks weird. Can you make it one line with the content, and use a `<br>` tag to break line?

2022-10-18 15:14 UTC, phazonoverload commented on content/library/videos/summer-2021/align-values-with-job.md
> +- Step 2: Check your emotions
Same here

2022-10-18 15:14 UTC, phazonoverload commented on content/library/videos/summer-2021/civil-engineering-ethics.md
> +Hundred years ago, civil engineering was very similar to how the tech industry is today. As the industrial revolution receded behind engineers, they found new ways to use the technologies they had de
```suggestion
A hundred years ago, civil engineering was very similar to how the tech industry is today. As the industrial revolution receded behind engineers, they found new ways to use the technologies they had developed. But as these projects became more ambitious, there was a rise in major engineering disasters due to questionable ethics. These disasters forced engineers to confront their shortcomings. As a result, they began to regulate themselves more intensely in established standardised industry codes of ethics. 
```

2022-10-18 15:14 UTC, phazonoverload commented on content/library/videos/summer-2022/overcoming-self-sabotage.md
> +We must pull the sabotaging behaviour into our conscious mind i.e. catch them in their pre-state. Although we still might choose sabotaging behaviour, the victory lies in making that behaviour delibe
```suggestion
To overcome sabotage, we must pull the sabotaging behaviour into our conscious mind i.e. catch them in their pre-state. Although we still might choose sabotaging behaviour, the victory lies in making that behaviour deliberate. As we get better at catching the sabotaging behaviour, we can then exercise our decisive powers to choose the new behaviour. Short-circuiting sabotaging bearings has a waterfall effect. Some sabotaging behaviours are connected; getting a handle on one leads to control over the others. Eventually, sabotage recognition gets easier and our new behaviours have a chance to establish in our subconscious.
```

2022-10-19 08:57 UTC, harshitajain165 commented
Thank you @phazonoverload, I've made the suggested changes.

2022-10-20 17:19 UTC, phazonoverload approved these changes

2022-10-20 17:19 UTC, merged